trigger:
- main   # or your branch name

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureCLI@2
  displayName: Upload static website files
  inputs:
    azureSubscription: 'azure-storage-connection'
    scriptType: bash
    scriptLocation: inlineScript
    inlineScript: |
      az storage blob upload-batch \
        --account-name test12387 \
        --destination '$web' \
        --source . \
        --overwrite
